@include('layouts.templatePayrole.head')
@include('layouts.templatePayrole.sidebar')
@include('layouts.templatePayrole.header')
@yield('content')
@include('layouts.templatePayrole.footer')
@include('layouts.templatePayrole.footer-scripts')