@include('layouts.templateAuditor.head')
@include('layouts.templateAuditor.sidebar')
@include('layouts.templateAuditor.header')
@yield('content')
@include('layouts.templateAuditor.footer')
@include('layouts.templateAuditor.footer-scripts')